version: '3.1'
services:
  db:
    image: postgres
    container_name: credi
    environment:
      POSTGRES_ROO_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTEGRES_DB: db-credi
    ports:
      - "5432:5432"
    volumes:
      - db-credi/var/lib/postgres
volumes:
  db-credi: