## NAME APLICATION ##
spring:
  application:
    name: credit-api
  datasource:
    url: jdbc:postgresql://localhost:5432/db-credi
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true

server:
  port: 8080


